# zsh configuration file

ZSHC="$(dirname "${BASH_SOURCE:-$0}")"
ZSH_CUSTOM="$ZSHC/custom"
ZSH="$ZSHC/oh-my-zsh"

DISABLE_AUTO_UPDATE=true
COMPLETION_WAITING_DOTS=true

plugins=(git archlinux undistract-me)

setopt completealiases
setopt histignoredups
setopt auto_pushd
unsetopt correct_all

source "$ZSH/oh-my-zsh.sh"
source "$ZSHC/zsh_theme"

if [ -f /usr/share/doc/pkgfile/command-not-found.zsh ]; then
	source /usr/share/doc/pkgfile/command-not-found.zsh
fi

if [ -f /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]; then
	source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

if [ -f "$ZSHC/zsh_sudo" ]; then
	while read -r COMMAND; do
		alias $COMMAND="sudo $COMMAND"
	done < "$ZSHC/zsh_sudo"
fi

if [ -f "$ZSHC/zsh_aliases" ]; then
	source "$ZSHC/zsh_aliases"
fi

if [ -f "$HOME/.dircolors" ]; then
	eval $(dircolors ~/.dircolors)
fi

if [[ $TERM == xterm-termite ]]; then
	. /etc/profile.d/vte.sh
	__vte_prompt_command
fi

export EDITOR=nano # Don't judge me!
export TERMINAL=termite
#export GPGKEY=5CFC3B88974EE250
export PAGER=less

export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${UID}/bus"

echo -en "\e[38;05;190m"
/usr/bin/figlet $(/usr/bin/hostname --short)
echo -en "\e[0m"

echo -e "\e[38;05;3m$(/usr/bin/fortune | /usr/bin/cowsay -f small)\e[0m"

if [ -f "$HOME/.ssh/id_ed25519" ]; then
	eval $(keychain --eval ~/.ssh/id_ed25519)
fi
